export const PAYMENTCART_LIST_ADD = "PAYMENTCART_LIST_ADD";
export const PAYMENTCART_LIST_MOMO = "PAYMENTCART_LIST_MOMO";
export const PAYMENTCART_LIST_PAYMENTONDELIVERY =
  "PAYMENTCART_LIST_PAYMENTONDELIVERY";
export const PAYMENTCART_LIST_REQUEST = "PAYMENTCART_LIST_REQUEST";

export const ORDER_DETAIL = "ORDER_DETAIL";
export const PAYMENTCART_UPDATE_MOMO_STATUS = "PAYMENTCART_UPDATE_MOMO_STATUS";