export const REGISTRATION_SELECT_EMAIL = "REGISTRATION_SELECT_EMAIL";
export const REGISTRATION_INSERT_EMAIL = "REGISTRATION_INSERT_EMAIL";
export const REGISTRATION_SEND_PASSWORDEMAIL =
  "REGISTRATION_SEND_PASSWORDEMAIL";

export const REGISTRATION_FAIL_PASSWORDEMAIL =
  "REGISTRATION_FAIL_PASSWORDEMAIL";
export const REGISTRATION_COLSE_ALERT = "REGISTRATION_COLSE_ALERT";

export const ACCOUNT_LIST_REQUEST = "ACCOUNT_LIST_REQUEST";
