export default {
  products: [
    {
      _id: "1",
      name: "Slim shirt",
      category: "Shirts",
      image: "/images/one.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {_id: "2",
      name: "Fit shirt",
      category: "Shirts",
      image: "/images/one.jpg",
      price: 50,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {_id: "3",
      name: "Best Pants",
      category: "Pants",
      image: "/images/one.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
  ],
};
